# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "applejag"
app_id = "firefly-jam-2026"
author_name = "Applejag"
app_name = "Firefly Jam 2026"
lang = "go"

[files]
firefly = { path = "assets/firefly-green-palettized.png" }
firefly-rev = { path = "assets/firefly-green-palettized-reverse.png" }
field = { path = "assets/field.png" }
racing-map = { path = "assets/race track sheet bg merged.png" }
racing-map-trees = { path = "assets/race track sheet trees.png" }
racing-map-treetops = { path = "assets/race track sheet trees top.png" }
racing-map-clouds = { path = "assets/race track sheet clouds.png" }
racing-map-mask = { path = "assets/race track mask.png" }
title-screen = { path = "assets/Title screen sheet.png" }
title-button-hi = { path = "assets/Title button highlight.png" }
title-no-continue = { path = "assets/Title no continue.png" }
transition = { path = "assets/transition.png" }
shop = { path = "assets/Frog_shop_mockup.png" }

eg_6x9 = { path = "assets/fonts/eg_6x9.fff" }
