# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "applejag"
app_id = "firefly-jam-2026"
author_name = "Applejag"
app_name = "Firefly Jam 2026"
lang = "go"

[files]
firefly = { path = "assets/firefly-green-palettized.png" }
firefly-rev = { path = "assets/firefly-green-palettized-reverse.png" }
field = { path = "assets/field.png" }
racing-map = { path = "assets/race track sheet bg merged.png" }
racing-map-trees = { path = "assets/race track sheet trees.png" }
racing-map-treetops = { path = "assets/race track sheet trees top.png" }
