# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "applejag"
app_id = "firefly-jam-2026"
author_name = "Applejag"
app_name = "Firefly Jam 2026"
lang = "go"

[files]
firefly = { path = "assets/firefly-green-palettized.png" }
firefly-rev = { path = "assets/firefly-green-palettized-reverse.png" }
field = { path = "assets/field.png" }
firefly-hi = { path = "assets/firefly-highlight.png" }
scroll = { path = "assets/scroll-sheet-reduced.png" }
racing-map = { path = "assets/race track sheet bg merged.png" }
racing-map-trees = { path = "assets/race track sheet trees.png" }
racing-map-treetops = { path = "assets/race track sheet trees top.png" }
racing-map-clouds = { path = "assets/race track sheet clouds.png" }
racing-map-mask = { path = "assets/race track mask.png" }
title-screen = { path = "assets/Title screen sheet.png" }
title-button-hi = { path = "assets/Title button highlight.png" }
title-no-continue = { path = "assets/Title no continue.png" }
transition = { path = "assets/transition.png" }
shop-bg = { path = "assets/frog shop bg.png" }
shop-frog = { path = "assets/frog shop frog.png" }
shop-props = { path = "assets/frog shop props.png" }
shop-chatbox = { path = "assets/Frog_shop_mockup_chat.png" }
shop-item = { path = "assets/Frog_shop_item.png" }
exit = { path = "assets/exit.png" }
cash-banner = { path = "assets/gold_and_ff_counters.png" }

eg_6x9 = { path = "assets/fonts/eg_6x9.fff" }
pico8_4x6 = { path = "assets/fonts/pico8_4x6.fff" }
