# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    "**/*.go",
    "**/*.proto",
    "assets/*.png",
    "assets/*.pxo",
]
SPDX-FileCopyrightText = "2026 Kalle Fagerberg"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "**/go.mod",
  "**/go.sum",
  "**/mise.lock",
]
SPDX-FileCopyrightText = "2026 Kalle Fagerberg"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "docs/**",
]
SPDX-FileCopyrightText = "2026 Kalle Fagerberg"
SPDX-License-Identifier = "CC-BY-4.0"
